/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as H4RouteImport } from './routes/h4'
import { Route as H3RouteImport } from './routes/h3'
import { Route as H2RouteImport } from './routes/h2'
import { Route as H1RouteImport } from './routes/h1'
import { Route as TryRouteRouteImport } from './routes/try/route'
import { Route as SbRouteRouteImport } from './routes/sb/route'
import { Route as GradeAnalysisRouteRouteImport } from './routes/grade-analysis/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as UsersLayoutRouteImport } from './routes/users/_layout'
import { Route as TestLoginDebugRouteImport } from './routes/test/login-debug'
import { Route as TestAuthMeRouteImport } from './routes/test/auth-me'
import { Route as SbLayoutRouteImport } from './routes/sb/_layout'
import { Route as OrderProductIdRouteImport } from './routes/order/$productId'
import { Route as OfficerLayoutRouteImport } from './routes/officer/_layout'
import { Route as GradeAnalysisLayoutRouteImport } from './routes/grade-analysis/_layout'
import { Route as ExploreUniversityRouteImport } from './routes/explore/university'
import { Route as ExploreRecruitmentUnitRouteImport } from './routes/explore/recruitment-unit'
import { Route as ExploreAdmissionRouteImport } from './routes/explore/admission'
import { Route as EvaluationLayoutRouteImport } from './routes/evaluation/_layout'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthOauthCallbackRouteImport } from './routes/auth/oauth/callback'

const UsersRouteImport = createFileRoute('/users')()
const OfficerRouteImport = createFileRoute('/officer')()
const EvaluationRouteImport = createFileRoute('/evaluation')()
const TryIndexLazyRouteImport = createFileRoute('/try/')()
const SbIndexLazyRouteImport = createFileRoute('/sb/')()
const GradeAnalysisIndexLazyRouteImport = createFileRoute('/grade-analysis/')()
const EvaluationIndexLazyRouteImport = createFileRoute('/evaluation/')()
const AnalysisIndexLazyRouteImport = createFileRoute('/analysis/')()
const SbDashboardLazyRouteImport = createFileRoute('/sb/dashboard')()
const OfficialGuideLazyRouteImport = createFileRoute('/official/guide')()
const OfficialFaqLazyRouteImport = createFileRoute('/official/faq')()
const ExploreSusiKyokwaLazyRouteImport = createFileRoute(
  '/explore/susi-kyokwa',
)()
const ExploreSusiJonghapLazyRouteImport = createFileRoute(
  '/explore/susi-jonghap',
)()
const ExplainServiceLazyRouteImport = createFileRoute('/explain/service')()
const ExplainRefundLazyRouteImport = createFileRoute('/explain/refund')()
const ExplainPrivacyLazyRouteImport = createFileRoute('/explain/privacy')()
const AnalysisPerformanceLazyRouteImport = createFileRoute(
  '/analysis/performance',
)()
const naverRedirectLazyRouteImport = createFileRoute('/(naver)/redirect')()
const OfficialNoticeIndexLazyRouteImport =
  createFileRoute('/official/notice/')()
const UsersLayoutSchoolRecordLazyRouteImport = createFileRoute(
  '/users/_layout/school-record',
)()
const UsersLayoutProfileLazyRouteImport = createFileRoute(
  '/users/_layout/profile',
)()
const UsersLayoutAdditionalFileLazyRouteImport = createFileRoute(
  '/users/_layout/additional-file',
)()
const SbLayoutTargetUniversityLazyRouteImport = createFileRoute(
  '/sb/_layout/target-university',
)()
const SbLayoutSubjectLazyRouteImport = createFileRoute('/sb/_layout/subject')()
const SbLayoutSetukLazyRouteImport = createFileRoute('/sb/_layout/setuk')()
const SbLayoutSchoolRecordLazyRouteImport = createFileRoute(
  '/sb/_layout/school-record',
)()
const SbLayoutRequestLazyRouteImport = createFileRoute('/sb/_layout/request')()
const SbLayoutPerformanceLazyRouteImport = createFileRoute(
  '/sb/_layout/performance',
)()
const SbLayoutNonsulLazyRouteImport = createFileRoute('/sb/_layout/nonsul')()
const SbLayoutMaterialAnalysisLazyRouteImport = createFileRoute(
  '/sb/_layout/material-analysis',
)()
const SbLayoutEvaluationListLazyRouteImport = createFileRoute(
  '/sb/_layout/evaluation-list',
)()
const SbLayoutEvaluationLazyRouteImport = createFileRoute(
  '/sb/_layout/evaluation',
)()
const SbLayoutCreativeActivityLazyRouteImport = createFileRoute(
  '/sb/_layout/creative-activity',
)()
const SbLayoutComprehensiveLazyRouteImport = createFileRoute(
  '/sb/_layout/comprehensive',
)()
const SbLayoutCompatibilityLazyRouteImport = createFileRoute(
  '/sb/_layout/compatibility',
)()
const SbLayoutBuildLazyRouteImport = createFileRoute('/sb/_layout/build')()
const SbLayoutAttendanceLazyRouteImport = createFileRoute(
  '/sb/_layout/attendance',
)()
const OfficialNoticePostIdLazyRouteImport = createFileRoute(
  '/official/notice/$postId',
)()
const OfficerLayoutProfileLazyRouteImport = createFileRoute(
  '/officer/_layout/profile',
)()
const GradeAnalysisLayoutSubjectLazyRouteImport = createFileRoute(
  '/grade-analysis/_layout/subject',
)()
const GradeAnalysisLayoutSchoolRecordLazyRouteImport = createFileRoute(
  '/grade-analysis/_layout/school-record',
)()
const GradeAnalysisLayoutRequestLazyRouteImport = createFileRoute(
  '/grade-analysis/_layout/request',
)()
const GradeAnalysisLayoutPerformanceLazyRouteImport = createFileRoute(
  '/grade-analysis/_layout/performance',
)()
const GradeAnalysisLayoutNonsulLazyRouteImport = createFileRoute(
  '/grade-analysis/_layout/nonsul',
)()
const GradeAnalysisLayoutEvaluationListLazyRouteImport = createFileRoute(
  '/grade-analysis/_layout/evaluation-list',
)()
const GradeAnalysisLayoutComprehensiveLazyRouteImport = createFileRoute(
  '/grade-analysis/_layout/comprehensive',
)()
const EvaluationLayoutRequestLazyRouteImport = createFileRoute(
  '/evaluation/_layout/request',
)()
const EvaluationLayoutListLazyRouteImport = createFileRoute(
  '/evaluation/_layout/list',
)()
const EvaluationLayoutCompatibilityLazyRouteImport = createFileRoute(
  '/evaluation/_layout/compatibility',
)()
const UsersLayoutPaymentIndexLazyRouteImport = createFileRoute(
  '/users/_layout/payment/',
)()
const OfficerLayoutApplyIndexLazyRouteImport = createFileRoute(
  '/officer/_layout/apply/',
)()
const EvaluationLayoutSelfIndexLazyRouteImport = createFileRoute(
  '/evaluation/_layout/self/',
)()
const UsersLayoutPaymentIdLazyRouteImport = createFileRoute(
  '/users/_layout/payment/$id',
)()
const OfficerLayoutApplyEvaluationIdLazyRouteImport = createFileRoute(
  '/officer/_layout/apply/$evaluationId',
)()

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerRoute = OfficerRouteImport.update({
  id: '/officer',
  path: '/officer',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const H4Route = H4RouteImport.update({
  id: '/h4',
  path: '/h4',
  getParentRoute: () => rootRouteImport,
} as any)
const H3Route = H3RouteImport.update({
  id: '/h3',
  path: '/h3',
  getParentRoute: () => rootRouteImport,
} as any)
const H2Route = H2RouteImport.update({
  id: '/h2',
  path: '/h2',
  getParentRoute: () => rootRouteImport,
} as any)
const H1Route = H1RouteImport.update({
  id: '/h1',
  path: '/h1',
  getParentRoute: () => rootRouteImport,
} as any)
const TryRouteRoute = TryRouteRouteImport.update({
  id: '/try',
  path: '/try',
  getParentRoute: () => rootRouteImport,
} as any)
const SbRouteRoute = SbRouteRouteImport.update({
  id: '/sb',
  path: '/sb',
  getParentRoute: () => rootRouteImport,
} as any)
const GradeAnalysisRouteRoute = GradeAnalysisRouteRouteImport.update({
  id: '/grade-analysis',
  path: '/grade-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TryIndexLazyRoute = TryIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TryRouteRoute,
} as any).lazy(() => import('./routes/try/index.lazy').then((d) => d.Route))
const SbIndexLazyRoute = SbIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SbRouteRoute,
} as any).lazy(() => import('./routes/sb/index.lazy').then((d) => d.Route))
const GradeAnalysisIndexLazyRoute = GradeAnalysisIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GradeAnalysisRouteRoute,
} as any).lazy(() =>
  import('./routes/grade-analysis/index.lazy').then((d) => d.Route),
)
const EvaluationIndexLazyRoute = EvaluationIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EvaluationRoute,
} as any).lazy(() =>
  import('./routes/evaluation/index.lazy').then((d) => d.Route),
)
const AnalysisIndexLazyRoute = AnalysisIndexLazyRouteImport.update({
  id: '/analysis/',
  path: '/analysis/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/analysis/index.lazy').then((d) => d.Route),
)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const SbDashboardLazyRoute = SbDashboardLazyRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SbRouteRoute,
} as any).lazy(() => import('./routes/sb/dashboard.lazy').then((d) => d.Route))
const OfficialGuideLazyRoute = OfficialGuideLazyRouteImport.update({
  id: '/official/guide',
  path: '/official/guide',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/official/guide.lazy').then((d) => d.Route),
)
const OfficialFaqLazyRoute = OfficialFaqLazyRouteImport.update({
  id: '/official/faq',
  path: '/official/faq',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/official/faq.lazy').then((d) => d.Route))
const ExploreSusiKyokwaLazyRoute = ExploreSusiKyokwaLazyRouteImport.update({
  id: '/explore/susi-kyokwa',
  path: '/explore/susi-kyokwa',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/explore/susi-kyokwa.lazy').then((d) => d.Route),
)
const ExploreSusiJonghapLazyRoute = ExploreSusiJonghapLazyRouteImport.update({
  id: '/explore/susi-jonghap',
  path: '/explore/susi-jonghap',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/explore/susi-jonghap.lazy').then((d) => d.Route),
)
const ExplainServiceLazyRoute = ExplainServiceLazyRouteImport.update({
  id: '/explain/service',
  path: '/explain/service',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/explain/service.lazy').then((d) => d.Route),
)
const ExplainRefundLazyRoute = ExplainRefundLazyRouteImport.update({
  id: '/explain/refund',
  path: '/explain/refund',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/explain/refund.lazy').then((d) => d.Route),
)
const ExplainPrivacyLazyRoute = ExplainPrivacyLazyRouteImport.update({
  id: '/explain/privacy',
  path: '/explain/privacy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/explain/privacy.lazy').then((d) => d.Route),
)
const AnalysisPerformanceLazyRoute = AnalysisPerformanceLazyRouteImport.update({
  id: '/analysis/performance',
  path: '/analysis/performance',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/analysis/performance.lazy').then((d) => d.Route),
)
const naverRedirectLazyRoute = naverRedirectLazyRouteImport
  .update({
    id: '/(naver)/redirect',
    path: '/redirect',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(naver)/redirect.lazy').then((d) => d.Route))
const UsersLayoutRoute = UsersLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => UsersRoute,
} as any)
const TestLoginDebugRoute = TestLoginDebugRouteImport.update({
  id: '/test/login-debug',
  path: '/test/login-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const TestAuthMeRoute = TestAuthMeRouteImport.update({
  id: '/test/auth-me',
  path: '/test/auth-me',
  getParentRoute: () => rootRouteImport,
} as any)
const SbLayoutRoute = SbLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => SbRouteRoute,
} as any)
const OrderProductIdRoute = OrderProductIdRouteImport.update({
  id: '/order/$productId',
  path: '/order/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerLayoutRoute = OfficerLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => OfficerRoute,
} as any)
const GradeAnalysisLayoutRoute = GradeAnalysisLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => GradeAnalysisRouteRoute,
} as any)
const ExploreUniversityRoute = ExploreUniversityRouteImport.update({
  id: '/explore/university',
  path: '/explore/university',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRecruitmentUnitRoute = ExploreRecruitmentUnitRouteImport.update({
  id: '/explore/recruitment-unit',
  path: '/explore/recruitment-unit',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreAdmissionRoute = ExploreAdmissionRouteImport.update({
  id: '/explore/admission',
  path: '/explore/admission',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationLayoutRoute = EvaluationLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => EvaluationRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficialNoticeIndexLazyRoute = OfficialNoticeIndexLazyRouteImport.update({
  id: '/official/notice/',
  path: '/official/notice/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/official/notice.index.lazy').then((d) => d.Route),
)
const UsersLayoutSchoolRecordLazyRoute =
  UsersLayoutSchoolRecordLazyRouteImport.update({
    id: '/school-record',
    path: '/school-record',
    getParentRoute: () => UsersLayoutRoute,
  } as any).lazy(() =>
    import('./routes/users/_layout/school-record.lazy').then((d) => d.Route),
  )
const UsersLayoutProfileLazyRoute = UsersLayoutProfileLazyRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UsersLayoutRoute,
} as any).lazy(() =>
  import('./routes/users/_layout/profile.lazy').then((d) => d.Route),
)
const UsersLayoutAdditionalFileLazyRoute =
  UsersLayoutAdditionalFileLazyRouteImport.update({
    id: '/additional-file',
    path: '/additional-file',
    getParentRoute: () => UsersLayoutRoute,
  } as any).lazy(() =>
    import('./routes/users/_layout/additional-file.lazy').then((d) => d.Route),
  )
const SbLayoutTargetUniversityLazyRoute =
  SbLayoutTargetUniversityLazyRouteImport.update({
    id: '/target-university',
    path: '/target-university',
    getParentRoute: () => SbLayoutRoute,
  } as any).lazy(() =>
    import('./routes/sb/_layout.target-university.lazy').then((d) => d.Route),
  )
const SbLayoutSubjectLazyRoute = SbLayoutSubjectLazyRouteImport.update({
  id: '/subject',
  path: '/subject',
  getParentRoute: () => SbLayoutRoute,
} as any).lazy(() =>
  import('./routes/sb/_layout.subject.lazy').then((d) => d.Route),
)
const SbLayoutSetukLazyRoute = SbLayoutSetukLazyRouteImport.update({
  id: '/setuk',
  path: '/setuk',
  getParentRoute: () => SbLayoutRoute,
} as any).lazy(() =>
  import('./routes/sb/_layout.setuk.lazy').then((d) => d.Route),
)
const SbLayoutSchoolRecordLazyRoute =
  SbLayoutSchoolRecordLazyRouteImport.update({
    id: '/school-record',
    path: '/school-record',
    getParentRoute: () => SbLayoutRoute,
  } as any).lazy(() =>
    import('./routes/sb/_layout.school-record.lazy').then((d) => d.Route),
  )
const SbLayoutRequestLazyRoute = SbLayoutRequestLazyRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => SbLayoutRoute,
} as any).lazy(() =>
  import('./routes/sb/_layout.request.lazy').then((d) => d.Route),
)
const SbLayoutPerformanceLazyRoute = SbLayoutPerformanceLazyRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => SbLayoutRoute,
} as any).lazy(() =>
  import('./routes/sb/_layout.performance.lazy').then((d) => d.Route),
)
const SbLayoutNonsulLazyRoute = SbLayoutNonsulLazyRouteImport.update({
  id: '/nonsul',
  path: '/nonsul',
  getParentRoute: () => SbLayoutRoute,
} as any).lazy(() =>
  import('./routes/sb/_layout.nonsul.lazy').then((d) => d.Route),
)
const SbLayoutMaterialAnalysisLazyRoute =
  SbLayoutMaterialAnalysisLazyRouteImport.update({
    id: '/material-analysis',
    path: '/material-analysis',
    getParentRoute: () => SbLayoutRoute,
  } as any).lazy(() =>
    import('./routes/sb/_layout.material-analysis.lazy').then((d) => d.Route),
  )
const SbLayoutEvaluationListLazyRoute =
  SbLayoutEvaluationListLazyRouteImport.update({
    id: '/evaluation-list',
    path: '/evaluation-list',
    getParentRoute: () => SbLayoutRoute,
  } as any).lazy(() =>
    import('./routes/sb/_layout.evaluation-list.lazy').then((d) => d.Route),
  )
const SbLayoutEvaluationLazyRoute = SbLayoutEvaluationLazyRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => SbLayoutRoute,
} as any).lazy(() =>
  import('./routes/sb/_layout.evaluation.lazy').then((d) => d.Route),
)
const SbLayoutCreativeActivityLazyRoute =
  SbLayoutCreativeActivityLazyRouteImport.update({
    id: '/creative-activity',
    path: '/creative-activity',
    getParentRoute: () => SbLayoutRoute,
  } as any).lazy(() =>
    import('./routes/sb/_layout.creative-activity.lazy').then((d) => d.Route),
  )
const SbLayoutComprehensiveLazyRoute =
  SbLayoutComprehensiveLazyRouteImport.update({
    id: '/comprehensive',
    path: '/comprehensive',
    getParentRoute: () => SbLayoutRoute,
  } as any).lazy(() =>
    import('./routes/sb/_layout.comprehensive.lazy').then((d) => d.Route),
  )
const SbLayoutCompatibilityLazyRoute =
  SbLayoutCompatibilityLazyRouteImport.update({
    id: '/compatibility',
    path: '/compatibility',
    getParentRoute: () => SbLayoutRoute,
  } as any).lazy(() =>
    import('./routes/sb/_layout.compatibility.lazy').then((d) => d.Route),
  )
const SbLayoutBuildLazyRoute = SbLayoutBuildLazyRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => SbLayoutRoute,
} as any).lazy(() =>
  import('./routes/sb/_layout.build.lazy').then((d) => d.Route),
)
const SbLayoutAttendanceLazyRoute = SbLayoutAttendanceLazyRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => SbLayoutRoute,
} as any).lazy(() =>
  import('./routes/sb/_layout.attendance.lazy').then((d) => d.Route),
)
const OfficialNoticePostIdLazyRoute =
  OfficialNoticePostIdLazyRouteImport.update({
    id: '/official/notice/$postId',
    path: '/official/notice/$postId',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/official/notice.$postId.lazy').then((d) => d.Route),
  )
const OfficerLayoutProfileLazyRoute =
  OfficerLayoutProfileLazyRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => OfficerLayoutRoute,
  } as any).lazy(() =>
    import('./routes/officer/_layout/profile.lazy').then((d) => d.Route),
  )
const GradeAnalysisLayoutSubjectLazyRoute =
  GradeAnalysisLayoutSubjectLazyRouteImport.update({
    id: '/subject',
    path: '/subject',
    getParentRoute: () => GradeAnalysisLayoutRoute,
  } as any).lazy(() =>
    import('./routes/grade-analysis/_layout.subject.lazy').then((d) => d.Route),
  )
const GradeAnalysisLayoutSchoolRecordLazyRoute =
  GradeAnalysisLayoutSchoolRecordLazyRouteImport.update({
    id: '/school-record',
    path: '/school-record',
    getParentRoute: () => GradeAnalysisLayoutRoute,
  } as any).lazy(() =>
    import('./routes/grade-analysis/_layout.school-record.lazy').then(
      (d) => d.Route,
    ),
  )
const GradeAnalysisLayoutRequestLazyRoute =
  GradeAnalysisLayoutRequestLazyRouteImport.update({
    id: '/request',
    path: '/request',
    getParentRoute: () => GradeAnalysisLayoutRoute,
  } as any).lazy(() =>
    import('./routes/grade-analysis/_layout.request.lazy').then((d) => d.Route),
  )
const GradeAnalysisLayoutPerformanceLazyRoute =
  GradeAnalysisLayoutPerformanceLazyRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => GradeAnalysisLayoutRoute,
  } as any).lazy(() =>
    import('./routes/grade-analysis/_layout.performance.lazy').then(
      (d) => d.Route,
    ),
  )
const GradeAnalysisLayoutNonsulLazyRoute =
  GradeAnalysisLayoutNonsulLazyRouteImport.update({
    id: '/nonsul',
    path: '/nonsul',
    getParentRoute: () => GradeAnalysisLayoutRoute,
  } as any).lazy(() =>
    import('./routes/grade-analysis/_layout.nonsul.lazy').then((d) => d.Route),
  )
const GradeAnalysisLayoutEvaluationListLazyRoute =
  GradeAnalysisLayoutEvaluationListLazyRouteImport.update({
    id: '/evaluation-list',
    path: '/evaluation-list',
    getParentRoute: () => GradeAnalysisLayoutRoute,
  } as any).lazy(() =>
    import('./routes/grade-analysis/_layout.evaluation-list.lazy').then(
      (d) => d.Route,
    ),
  )
const GradeAnalysisLayoutComprehensiveLazyRoute =
  GradeAnalysisLayoutComprehensiveLazyRouteImport.update({
    id: '/comprehensive',
    path: '/comprehensive',
    getParentRoute: () => GradeAnalysisLayoutRoute,
  } as any).lazy(() =>
    import('./routes/grade-analysis/_layout.comprehensive.lazy').then(
      (d) => d.Route,
    ),
  )
const EvaluationLayoutRequestLazyRoute =
  EvaluationLayoutRequestLazyRouteImport.update({
    id: '/request',
    path: '/request',
    getParentRoute: () => EvaluationLayoutRoute,
  } as any).lazy(() =>
    import('./routes/evaluation/_layout/request.lazy').then((d) => d.Route),
  )
const EvaluationLayoutListLazyRoute =
  EvaluationLayoutListLazyRouteImport.update({
    id: '/list',
    path: '/list',
    getParentRoute: () => EvaluationLayoutRoute,
  } as any).lazy(() =>
    import('./routes/evaluation/_layout/list.lazy').then((d) => d.Route),
  )
const EvaluationLayoutCompatibilityLazyRoute =
  EvaluationLayoutCompatibilityLazyRouteImport.update({
    id: '/compatibility',
    path: '/compatibility',
    getParentRoute: () => EvaluationLayoutRoute,
  } as any).lazy(() =>
    import('./routes/evaluation/_layout/compatibility.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthOauthCallbackRoute = AuthOauthCallbackRouteImport.update({
  id: '/auth/oauth/callback',
  path: '/auth/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersLayoutPaymentIndexLazyRoute =
  UsersLayoutPaymentIndexLazyRouteImport.update({
    id: '/payment/',
    path: '/payment/',
    getParentRoute: () => UsersLayoutRoute,
  } as any).lazy(() =>
    import('./routes/users/_layout/payment.index.lazy').then((d) => d.Route),
  )
const OfficerLayoutApplyIndexLazyRoute =
  OfficerLayoutApplyIndexLazyRouteImport.update({
    id: '/apply/',
    path: '/apply/',
    getParentRoute: () => OfficerLayoutRoute,
  } as any).lazy(() =>
    import('./routes/officer/_layout/apply.index.lazy').then((d) => d.Route),
  )
const EvaluationLayoutSelfIndexLazyRoute =
  EvaluationLayoutSelfIndexLazyRouteImport.update({
    id: '/self/',
    path: '/self/',
    getParentRoute: () => EvaluationLayoutRoute,
  } as any).lazy(() =>
    import('./routes/evaluation/_layout/self.index.lazy').then((d) => d.Route),
  )
const UsersLayoutPaymentIdLazyRoute =
  UsersLayoutPaymentIdLazyRouteImport.update({
    id: '/payment/$id',
    path: '/payment/$id',
    getParentRoute: () => UsersLayoutRoute,
  } as any).lazy(() =>
    import('./routes/users/_layout/payment.$id.lazy').then((d) => d.Route),
  )
const OfficerLayoutApplyEvaluationIdLazyRoute =
  OfficerLayoutApplyEvaluationIdLazyRouteImport.update({
    id: '/apply/$evaluationId',
    path: '/apply/$evaluationId',
    getParentRoute: () => OfficerLayoutRoute,
  } as any).lazy(() =>
    import('./routes/officer/_layout/apply.$evaluationId.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/grade-analysis': typeof GradeAnalysisLayoutRouteWithChildren
  '/sb': typeof SbLayoutRouteWithChildren
  '/try': typeof TryRouteRouteWithChildren
  '/h1': typeof H1Route
  '/h2': typeof H2Route
  '/h3': typeof H3Route
  '/h4': typeof H4Route
  '/pricing': typeof PricingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/evaluation': typeof EvaluationLayoutRouteWithChildren
  '/explore/admission': typeof ExploreAdmissionRoute
  '/explore/recruitment-unit': typeof ExploreRecruitmentUnitRoute
  '/explore/university': typeof ExploreUniversityRoute
  '/officer': typeof OfficerLayoutRouteWithChildren
  '/order/$productId': typeof OrderProductIdRoute
  '/test/auth-me': typeof TestAuthMeRoute
  '/test/login-debug': typeof TestLoginDebugRoute
  '/users': typeof UsersLayoutRouteWithChildren
  '/redirect': typeof naverRedirectLazyRoute
  '/analysis/performance': typeof AnalysisPerformanceLazyRoute
  '/explain/privacy': typeof ExplainPrivacyLazyRoute
  '/explain/refund': typeof ExplainRefundLazyRoute
  '/explain/service': typeof ExplainServiceLazyRoute
  '/explore/susi-jonghap': typeof ExploreSusiJonghapLazyRoute
  '/explore/susi-kyokwa': typeof ExploreSusiKyokwaLazyRoute
  '/official/faq': typeof OfficialFaqLazyRoute
  '/official/guide': typeof OfficialGuideLazyRoute
  '/sb/dashboard': typeof SbDashboardLazyRoute
  '/products': typeof ProductsIndexRoute
  '/analysis': typeof AnalysisIndexLazyRoute
  '/evaluation/': typeof EvaluationIndexLazyRoute
  '/grade-analysis/': typeof GradeAnalysisIndexLazyRoute
  '/sb/': typeof SbIndexLazyRoute
  '/try/': typeof TryIndexLazyRoute
  '/auth/oauth/callback': typeof AuthOauthCallbackRoute
  '/evaluation/compatibility': typeof EvaluationLayoutCompatibilityLazyRoute
  '/evaluation/list': typeof EvaluationLayoutListLazyRoute
  '/evaluation/request': typeof EvaluationLayoutRequestLazyRoute
  '/grade-analysis/comprehensive': typeof GradeAnalysisLayoutComprehensiveLazyRoute
  '/grade-analysis/evaluation-list': typeof GradeAnalysisLayoutEvaluationListLazyRoute
  '/grade-analysis/nonsul': typeof GradeAnalysisLayoutNonsulLazyRoute
  '/grade-analysis/performance': typeof GradeAnalysisLayoutPerformanceLazyRoute
  '/grade-analysis/request': typeof GradeAnalysisLayoutRequestLazyRoute
  '/grade-analysis/school-record': typeof GradeAnalysisLayoutSchoolRecordLazyRoute
  '/grade-analysis/subject': typeof GradeAnalysisLayoutSubjectLazyRoute
  '/officer/profile': typeof OfficerLayoutProfileLazyRoute
  '/official/notice/$postId': typeof OfficialNoticePostIdLazyRoute
  '/sb/attendance': typeof SbLayoutAttendanceLazyRoute
  '/sb/build': typeof SbLayoutBuildLazyRoute
  '/sb/compatibility': typeof SbLayoutCompatibilityLazyRoute
  '/sb/comprehensive': typeof SbLayoutComprehensiveLazyRoute
  '/sb/creative-activity': typeof SbLayoutCreativeActivityLazyRoute
  '/sb/evaluation': typeof SbLayoutEvaluationLazyRoute
  '/sb/evaluation-list': typeof SbLayoutEvaluationListLazyRoute
  '/sb/material-analysis': typeof SbLayoutMaterialAnalysisLazyRoute
  '/sb/nonsul': typeof SbLayoutNonsulLazyRoute
  '/sb/performance': typeof SbLayoutPerformanceLazyRoute
  '/sb/request': typeof SbLayoutRequestLazyRoute
  '/sb/school-record': typeof SbLayoutSchoolRecordLazyRoute
  '/sb/setuk': typeof SbLayoutSetukLazyRoute
  '/sb/subject': typeof SbLayoutSubjectLazyRoute
  '/sb/target-university': typeof SbLayoutTargetUniversityLazyRoute
  '/users/additional-file': typeof UsersLayoutAdditionalFileLazyRoute
  '/users/profile': typeof UsersLayoutProfileLazyRoute
  '/users/school-record': typeof UsersLayoutSchoolRecordLazyRoute
  '/official/notice': typeof OfficialNoticeIndexLazyRoute
  '/officer/apply/$evaluationId': typeof OfficerLayoutApplyEvaluationIdLazyRoute
  '/users/payment/$id': typeof UsersLayoutPaymentIdLazyRoute
  '/evaluation/self': typeof EvaluationLayoutSelfIndexLazyRoute
  '/officer/apply': typeof OfficerLayoutApplyIndexLazyRoute
  '/users/payment': typeof UsersLayoutPaymentIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/h1': typeof H1Route
  '/h2': typeof H2Route
  '/h3': typeof H3Route
  '/h4': typeof H4Route
  '/pricing': typeof PricingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/evaluation': typeof EvaluationIndexLazyRoute
  '/explore/admission': typeof ExploreAdmissionRoute
  '/explore/recruitment-unit': typeof ExploreRecruitmentUnitRoute
  '/explore/university': typeof ExploreUniversityRoute
  '/grade-analysis': typeof GradeAnalysisIndexLazyRoute
  '/officer': typeof OfficerLayoutRouteWithChildren
  '/order/$productId': typeof OrderProductIdRoute
  '/sb': typeof SbIndexLazyRoute
  '/test/auth-me': typeof TestAuthMeRoute
  '/test/login-debug': typeof TestLoginDebugRoute
  '/users': typeof UsersLayoutRouteWithChildren
  '/redirect': typeof naverRedirectLazyRoute
  '/analysis/performance': typeof AnalysisPerformanceLazyRoute
  '/explain/privacy': typeof ExplainPrivacyLazyRoute
  '/explain/refund': typeof ExplainRefundLazyRoute
  '/explain/service': typeof ExplainServiceLazyRoute
  '/explore/susi-jonghap': typeof ExploreSusiJonghapLazyRoute
  '/explore/susi-kyokwa': typeof ExploreSusiKyokwaLazyRoute
  '/official/faq': typeof OfficialFaqLazyRoute
  '/official/guide': typeof OfficialGuideLazyRoute
  '/sb/dashboard': typeof SbDashboardLazyRoute
  '/products': typeof ProductsIndexRoute
  '/analysis': typeof AnalysisIndexLazyRoute
  '/try': typeof TryIndexLazyRoute
  '/auth/oauth/callback': typeof AuthOauthCallbackRoute
  '/evaluation/compatibility': typeof EvaluationLayoutCompatibilityLazyRoute
  '/evaluation/list': typeof EvaluationLayoutListLazyRoute
  '/evaluation/request': typeof EvaluationLayoutRequestLazyRoute
  '/grade-analysis/comprehensive': typeof GradeAnalysisLayoutComprehensiveLazyRoute
  '/grade-analysis/evaluation-list': typeof GradeAnalysisLayoutEvaluationListLazyRoute
  '/grade-analysis/nonsul': typeof GradeAnalysisLayoutNonsulLazyRoute
  '/grade-analysis/performance': typeof GradeAnalysisLayoutPerformanceLazyRoute
  '/grade-analysis/request': typeof GradeAnalysisLayoutRequestLazyRoute
  '/grade-analysis/school-record': typeof GradeAnalysisLayoutSchoolRecordLazyRoute
  '/grade-analysis/subject': typeof GradeAnalysisLayoutSubjectLazyRoute
  '/officer/profile': typeof OfficerLayoutProfileLazyRoute
  '/official/notice/$postId': typeof OfficialNoticePostIdLazyRoute
  '/sb/attendance': typeof SbLayoutAttendanceLazyRoute
  '/sb/build': typeof SbLayoutBuildLazyRoute
  '/sb/compatibility': typeof SbLayoutCompatibilityLazyRoute
  '/sb/comprehensive': typeof SbLayoutComprehensiveLazyRoute
  '/sb/creative-activity': typeof SbLayoutCreativeActivityLazyRoute
  '/sb/evaluation': typeof SbLayoutEvaluationLazyRoute
  '/sb/evaluation-list': typeof SbLayoutEvaluationListLazyRoute
  '/sb/material-analysis': typeof SbLayoutMaterialAnalysisLazyRoute
  '/sb/nonsul': typeof SbLayoutNonsulLazyRoute
  '/sb/performance': typeof SbLayoutPerformanceLazyRoute
  '/sb/request': typeof SbLayoutRequestLazyRoute
  '/sb/school-record': typeof SbLayoutSchoolRecordLazyRoute
  '/sb/setuk': typeof SbLayoutSetukLazyRoute
  '/sb/subject': typeof SbLayoutSubjectLazyRoute
  '/sb/target-university': typeof SbLayoutTargetUniversityLazyRoute
  '/users/additional-file': typeof UsersLayoutAdditionalFileLazyRoute
  '/users/profile': typeof UsersLayoutProfileLazyRoute
  '/users/school-record': typeof UsersLayoutSchoolRecordLazyRoute
  '/official/notice': typeof OfficialNoticeIndexLazyRoute
  '/officer/apply/$evaluationId': typeof OfficerLayoutApplyEvaluationIdLazyRoute
  '/users/payment/$id': typeof UsersLayoutPaymentIdLazyRoute
  '/evaluation/self': typeof EvaluationLayoutSelfIndexLazyRoute
  '/officer/apply': typeof OfficerLayoutApplyIndexLazyRoute
  '/users/payment': typeof UsersLayoutPaymentIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/grade-analysis': typeof GradeAnalysisRouteRouteWithChildren
  '/sb': typeof SbRouteRouteWithChildren
  '/try': typeof TryRouteRouteWithChildren
  '/h1': typeof H1Route
  '/h2': typeof H2Route
  '/h3': typeof H3Route
  '/h4': typeof H4Route
  '/pricing': typeof PricingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/evaluation': typeof EvaluationRouteWithChildren
  '/evaluation/_layout': typeof EvaluationLayoutRouteWithChildren
  '/explore/admission': typeof ExploreAdmissionRoute
  '/explore/recruitment-unit': typeof ExploreRecruitmentUnitRoute
  '/explore/university': typeof ExploreUniversityRoute
  '/grade-analysis/_layout': typeof GradeAnalysisLayoutRouteWithChildren
  '/officer': typeof OfficerRouteWithChildren
  '/officer/_layout': typeof OfficerLayoutRouteWithChildren
  '/order/$productId': typeof OrderProductIdRoute
  '/sb/_layout': typeof SbLayoutRouteWithChildren
  '/test/auth-me': typeof TestAuthMeRoute
  '/test/login-debug': typeof TestLoginDebugRoute
  '/users': typeof UsersRouteWithChildren
  '/users/_layout': typeof UsersLayoutRouteWithChildren
  '/(naver)/redirect': typeof naverRedirectLazyRoute
  '/analysis/performance': typeof AnalysisPerformanceLazyRoute
  '/explain/privacy': typeof ExplainPrivacyLazyRoute
  '/explain/refund': typeof ExplainRefundLazyRoute
  '/explain/service': typeof ExplainServiceLazyRoute
  '/explore/susi-jonghap': typeof ExploreSusiJonghapLazyRoute
  '/explore/susi-kyokwa': typeof ExploreSusiKyokwaLazyRoute
  '/official/faq': typeof OfficialFaqLazyRoute
  '/official/guide': typeof OfficialGuideLazyRoute
  '/sb/dashboard': typeof SbDashboardLazyRoute
  '/products/': typeof ProductsIndexRoute
  '/analysis/': typeof AnalysisIndexLazyRoute
  '/evaluation/': typeof EvaluationIndexLazyRoute
  '/grade-analysis/': typeof GradeAnalysisIndexLazyRoute
  '/sb/': typeof SbIndexLazyRoute
  '/try/': typeof TryIndexLazyRoute
  '/auth/oauth/callback': typeof AuthOauthCallbackRoute
  '/evaluation/_layout/compatibility': typeof EvaluationLayoutCompatibilityLazyRoute
  '/evaluation/_layout/list': typeof EvaluationLayoutListLazyRoute
  '/evaluation/_layout/request': typeof EvaluationLayoutRequestLazyRoute
  '/grade-analysis/_layout/comprehensive': typeof GradeAnalysisLayoutComprehensiveLazyRoute
  '/grade-analysis/_layout/evaluation-list': typeof GradeAnalysisLayoutEvaluationListLazyRoute
  '/grade-analysis/_layout/nonsul': typeof GradeAnalysisLayoutNonsulLazyRoute
  '/grade-analysis/_layout/performance': typeof GradeAnalysisLayoutPerformanceLazyRoute
  '/grade-analysis/_layout/request': typeof GradeAnalysisLayoutRequestLazyRoute
  '/grade-analysis/_layout/school-record': typeof GradeAnalysisLayoutSchoolRecordLazyRoute
  '/grade-analysis/_layout/subject': typeof GradeAnalysisLayoutSubjectLazyRoute
  '/officer/_layout/profile': typeof OfficerLayoutProfileLazyRoute
  '/official/notice/$postId': typeof OfficialNoticePostIdLazyRoute
  '/sb/_layout/attendance': typeof SbLayoutAttendanceLazyRoute
  '/sb/_layout/build': typeof SbLayoutBuildLazyRoute
  '/sb/_layout/compatibility': typeof SbLayoutCompatibilityLazyRoute
  '/sb/_layout/comprehensive': typeof SbLayoutComprehensiveLazyRoute
  '/sb/_layout/creative-activity': typeof SbLayoutCreativeActivityLazyRoute
  '/sb/_layout/evaluation': typeof SbLayoutEvaluationLazyRoute
  '/sb/_layout/evaluation-list': typeof SbLayoutEvaluationListLazyRoute
  '/sb/_layout/material-analysis': typeof SbLayoutMaterialAnalysisLazyRoute
  '/sb/_layout/nonsul': typeof SbLayoutNonsulLazyRoute
  '/sb/_layout/performance': typeof SbLayoutPerformanceLazyRoute
  '/sb/_layout/request': typeof SbLayoutRequestLazyRoute
  '/sb/_layout/school-record': typeof SbLayoutSchoolRecordLazyRoute
  '/sb/_layout/setuk': typeof SbLayoutSetukLazyRoute
  '/sb/_layout/subject': typeof SbLayoutSubjectLazyRoute
  '/sb/_layout/target-university': typeof SbLayoutTargetUniversityLazyRoute
  '/users/_layout/additional-file': typeof UsersLayoutAdditionalFileLazyRoute
  '/users/_layout/profile': typeof UsersLayoutProfileLazyRoute
  '/users/_layout/school-record': typeof UsersLayoutSchoolRecordLazyRoute
  '/official/notice/': typeof OfficialNoticeIndexLazyRoute
  '/officer/_layout/apply/$evaluationId': typeof OfficerLayoutApplyEvaluationIdLazyRoute
  '/users/_layout/payment/$id': typeof UsersLayoutPaymentIdLazyRoute
  '/evaluation/_layout/self/': typeof EvaluationLayoutSelfIndexLazyRoute
  '/officer/_layout/apply/': typeof OfficerLayoutApplyIndexLazyRoute
  '/users/_layout/payment/': typeof UsersLayoutPaymentIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/grade-analysis'
    | '/sb'
    | '/try'
    | '/h1'
    | '/h2'
    | '/h3'
    | '/h4'
    | '/pricing'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/evaluation'
    | '/explore/admission'
    | '/explore/recruitment-unit'
    | '/explore/university'
    | '/officer'
    | '/order/$productId'
    | '/test/auth-me'
    | '/test/login-debug'
    | '/users'
    | '/redirect'
    | '/analysis/performance'
    | '/explain/privacy'
    | '/explain/refund'
    | '/explain/service'
    | '/explore/susi-jonghap'
    | '/explore/susi-kyokwa'
    | '/official/faq'
    | '/official/guide'
    | '/sb/dashboard'
    | '/products'
    | '/analysis'
    | '/evaluation/'
    | '/grade-analysis/'
    | '/sb/'
    | '/try/'
    | '/auth/oauth/callback'
    | '/evaluation/compatibility'
    | '/evaluation/list'
    | '/evaluation/request'
    | '/grade-analysis/comprehensive'
    | '/grade-analysis/evaluation-list'
    | '/grade-analysis/nonsul'
    | '/grade-analysis/performance'
    | '/grade-analysis/request'
    | '/grade-analysis/school-record'
    | '/grade-analysis/subject'
    | '/officer/profile'
    | '/official/notice/$postId'
    | '/sb/attendance'
    | '/sb/build'
    | '/sb/compatibility'
    | '/sb/comprehensive'
    | '/sb/creative-activity'
    | '/sb/evaluation'
    | '/sb/evaluation-list'
    | '/sb/material-analysis'
    | '/sb/nonsul'
    | '/sb/performance'
    | '/sb/request'
    | '/sb/school-record'
    | '/sb/setuk'
    | '/sb/subject'
    | '/sb/target-university'
    | '/users/additional-file'
    | '/users/profile'
    | '/users/school-record'
    | '/official/notice'
    | '/officer/apply/$evaluationId'
    | '/users/payment/$id'
    | '/evaluation/self'
    | '/officer/apply'
    | '/users/payment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/h1'
    | '/h2'
    | '/h3'
    | '/h4'
    | '/pricing'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/evaluation'
    | '/explore/admission'
    | '/explore/recruitment-unit'
    | '/explore/university'
    | '/grade-analysis'
    | '/officer'
    | '/order/$productId'
    | '/sb'
    | '/test/auth-me'
    | '/test/login-debug'
    | '/users'
    | '/redirect'
    | '/analysis/performance'
    | '/explain/privacy'
    | '/explain/refund'
    | '/explain/service'
    | '/explore/susi-jonghap'
    | '/explore/susi-kyokwa'
    | '/official/faq'
    | '/official/guide'
    | '/sb/dashboard'
    | '/products'
    | '/analysis'
    | '/try'
    | '/auth/oauth/callback'
    | '/evaluation/compatibility'
    | '/evaluation/list'
    | '/evaluation/request'
    | '/grade-analysis/comprehensive'
    | '/grade-analysis/evaluation-list'
    | '/grade-analysis/nonsul'
    | '/grade-analysis/performance'
    | '/grade-analysis/request'
    | '/grade-analysis/school-record'
    | '/grade-analysis/subject'
    | '/officer/profile'
    | '/official/notice/$postId'
    | '/sb/attendance'
    | '/sb/build'
    | '/sb/compatibility'
    | '/sb/comprehensive'
    | '/sb/creative-activity'
    | '/sb/evaluation'
    | '/sb/evaluation-list'
    | '/sb/material-analysis'
    | '/sb/nonsul'
    | '/sb/performance'
    | '/sb/request'
    | '/sb/school-record'
    | '/sb/setuk'
    | '/sb/subject'
    | '/sb/target-university'
    | '/users/additional-file'
    | '/users/profile'
    | '/users/school-record'
    | '/official/notice'
    | '/officer/apply/$evaluationId'
    | '/users/payment/$id'
    | '/evaluation/self'
    | '/officer/apply'
    | '/users/payment'
  id:
    | '__root__'
    | '/'
    | '/grade-analysis'
    | '/sb'
    | '/try'
    | '/h1'
    | '/h2'
    | '/h3'
    | '/h4'
    | '/pricing'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/evaluation'
    | '/evaluation/_layout'
    | '/explore/admission'
    | '/explore/recruitment-unit'
    | '/explore/university'
    | '/grade-analysis/_layout'
    | '/officer'
    | '/officer/_layout'
    | '/order/$productId'
    | '/sb/_layout'
    | '/test/auth-me'
    | '/test/login-debug'
    | '/users'
    | '/users/_layout'
    | '/(naver)/redirect'
    | '/analysis/performance'
    | '/explain/privacy'
    | '/explain/refund'
    | '/explain/service'
    | '/explore/susi-jonghap'
    | '/explore/susi-kyokwa'
    | '/official/faq'
    | '/official/guide'
    | '/sb/dashboard'
    | '/products/'
    | '/analysis/'
    | '/evaluation/'
    | '/grade-analysis/'
    | '/sb/'
    | '/try/'
    | '/auth/oauth/callback'
    | '/evaluation/_layout/compatibility'
    | '/evaluation/_layout/list'
    | '/evaluation/_layout/request'
    | '/grade-analysis/_layout/comprehensive'
    | '/grade-analysis/_layout/evaluation-list'
    | '/grade-analysis/_layout/nonsul'
    | '/grade-analysis/_layout/performance'
    | '/grade-analysis/_layout/request'
    | '/grade-analysis/_layout/school-record'
    | '/grade-analysis/_layout/subject'
    | '/officer/_layout/profile'
    | '/official/notice/$postId'
    | '/sb/_layout/attendance'
    | '/sb/_layout/build'
    | '/sb/_layout/compatibility'
    | '/sb/_layout/comprehensive'
    | '/sb/_layout/creative-activity'
    | '/sb/_layout/evaluation'
    | '/sb/_layout/evaluation-list'
    | '/sb/_layout/material-analysis'
    | '/sb/_layout/nonsul'
    | '/sb/_layout/performance'
    | '/sb/_layout/request'
    | '/sb/_layout/school-record'
    | '/sb/_layout/setuk'
    | '/sb/_layout/subject'
    | '/sb/_layout/target-university'
    | '/users/_layout/additional-file'
    | '/users/_layout/profile'
    | '/users/_layout/school-record'
    | '/official/notice/'
    | '/officer/_layout/apply/$evaluationId'
    | '/users/_layout/payment/$id'
    | '/evaluation/_layout/self/'
    | '/officer/_layout/apply/'
    | '/users/_layout/payment/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GradeAnalysisRouteRoute: typeof GradeAnalysisRouteRouteWithChildren
  SbRouteRoute: typeof SbRouteRouteWithChildren
  TryRouteRoute: typeof TryRouteRouteWithChildren
  H1Route: typeof H1Route
  H2Route: typeof H2Route
  H3Route: typeof H3Route
  H4Route: typeof H4Route
  PricingRoute: typeof PricingRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  EvaluationRoute: typeof EvaluationRouteWithChildren
  ExploreAdmissionRoute: typeof ExploreAdmissionRoute
  ExploreRecruitmentUnitRoute: typeof ExploreRecruitmentUnitRoute
  ExploreUniversityRoute: typeof ExploreUniversityRoute
  OfficerRoute: typeof OfficerRouteWithChildren
  OrderProductIdRoute: typeof OrderProductIdRoute
  TestAuthMeRoute: typeof TestAuthMeRoute
  TestLoginDebugRoute: typeof TestLoginDebugRoute
  UsersRoute: typeof UsersRouteWithChildren
  naverRedirectLazyRoute: typeof naverRedirectLazyRoute
  AnalysisPerformanceLazyRoute: typeof AnalysisPerformanceLazyRoute
  ExplainPrivacyLazyRoute: typeof ExplainPrivacyLazyRoute
  ExplainRefundLazyRoute: typeof ExplainRefundLazyRoute
  ExplainServiceLazyRoute: typeof ExplainServiceLazyRoute
  ExploreSusiJonghapLazyRoute: typeof ExploreSusiJonghapLazyRoute
  ExploreSusiKyokwaLazyRoute: typeof ExploreSusiKyokwaLazyRoute
  OfficialFaqLazyRoute: typeof OfficialFaqLazyRoute
  OfficialGuideLazyRoute: typeof OfficialGuideLazyRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  AnalysisIndexLazyRoute: typeof AnalysisIndexLazyRoute
  AuthOauthCallbackRoute: typeof AuthOauthCallbackRoute
  OfficialNoticePostIdLazyRoute: typeof OfficialNoticePostIdLazyRoute
  OfficialNoticeIndexLazyRoute: typeof OfficialNoticeIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer': {
      id: '/officer'
      path: '/officer'
      fullPath: '/officer'
      preLoaderRoute: typeof OfficerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h4': {
      id: '/h4'
      path: '/h4'
      fullPath: '/h4'
      preLoaderRoute: typeof H4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h3': {
      id: '/h3'
      path: '/h3'
      fullPath: '/h3'
      preLoaderRoute: typeof H3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h2': {
      id: '/h2'
      path: '/h2'
      fullPath: '/h2'
      preLoaderRoute: typeof H2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h1': {
      id: '/h1'
      path: '/h1'
      fullPath: '/h1'
      preLoaderRoute: typeof H1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/try': {
      id: '/try'
      path: '/try'
      fullPath: '/try'
      preLoaderRoute: typeof TryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sb': {
      id: '/sb'
      path: '/sb'
      fullPath: '/sb'
      preLoaderRoute: typeof SbRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grade-analysis': {
      id: '/grade-analysis'
      path: '/grade-analysis'
      fullPath: '/grade-analysis'
      preLoaderRoute: typeof GradeAnalysisRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/try/': {
      id: '/try/'
      path: '/'
      fullPath: '/try/'
      preLoaderRoute: typeof TryIndexLazyRouteImport
      parentRoute: typeof TryRouteRoute
    }
    '/sb/': {
      id: '/sb/'
      path: '/'
      fullPath: '/sb/'
      preLoaderRoute: typeof SbIndexLazyRouteImport
      parentRoute: typeof SbRouteRoute
    }
    '/grade-analysis/': {
      id: '/grade-analysis/'
      path: '/'
      fullPath: '/grade-analysis/'
      preLoaderRoute: typeof GradeAnalysisIndexLazyRouteImport
      parentRoute: typeof GradeAnalysisRouteRoute
    }
    '/evaluation/': {
      id: '/evaluation/'
      path: '/'
      fullPath: '/evaluation/'
      preLoaderRoute: typeof EvaluationIndexLazyRouteImport
      parentRoute: typeof EvaluationRoute
    }
    '/analysis/': {
      id: '/analysis/'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sb/dashboard': {
      id: '/sb/dashboard'
      path: '/dashboard'
      fullPath: '/sb/dashboard'
      preLoaderRoute: typeof SbDashboardLazyRouteImport
      parentRoute: typeof SbRouteRoute
    }
    '/official/guide': {
      id: '/official/guide'
      path: '/official/guide'
      fullPath: '/official/guide'
      preLoaderRoute: typeof OfficialGuideLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/official/faq': {
      id: '/official/faq'
      path: '/official/faq'
      fullPath: '/official/faq'
      preLoaderRoute: typeof OfficialFaqLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/susi-kyokwa': {
      id: '/explore/susi-kyokwa'
      path: '/explore/susi-kyokwa'
      fullPath: '/explore/susi-kyokwa'
      preLoaderRoute: typeof ExploreSusiKyokwaLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/susi-jonghap': {
      id: '/explore/susi-jonghap'
      path: '/explore/susi-jonghap'
      fullPath: '/explore/susi-jonghap'
      preLoaderRoute: typeof ExploreSusiJonghapLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explain/service': {
      id: '/explain/service'
      path: '/explain/service'
      fullPath: '/explain/service'
      preLoaderRoute: typeof ExplainServiceLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explain/refund': {
      id: '/explain/refund'
      path: '/explain/refund'
      fullPath: '/explain/refund'
      preLoaderRoute: typeof ExplainRefundLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explain/privacy': {
      id: '/explain/privacy'
      path: '/explain/privacy'
      fullPath: '/explain/privacy'
      preLoaderRoute: typeof ExplainPrivacyLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/performance': {
      id: '/analysis/performance'
      path: '/analysis/performance'
      fullPath: '/analysis/performance'
      preLoaderRoute: typeof AnalysisPerformanceLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(naver)/redirect': {
      id: '/(naver)/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof naverRedirectLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/_layout': {
      id: '/users/_layout'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersLayoutRouteImport
      parentRoute: typeof UsersRoute
    }
    '/test/login-debug': {
      id: '/test/login-debug'
      path: '/test/login-debug'
      fullPath: '/test/login-debug'
      preLoaderRoute: typeof TestLoginDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/auth-me': {
      id: '/test/auth-me'
      path: '/test/auth-me'
      fullPath: '/test/auth-me'
      preLoaderRoute: typeof TestAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sb/_layout': {
      id: '/sb/_layout'
      path: ''
      fullPath: '/sb'
      preLoaderRoute: typeof SbLayoutRouteImport
      parentRoute: typeof SbRouteRoute
    }
    '/order/$productId': {
      id: '/order/$productId'
      path: '/order/$productId'
      fullPath: '/order/$productId'
      preLoaderRoute: typeof OrderProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/_layout': {
      id: '/officer/_layout'
      path: '/officer'
      fullPath: '/officer'
      preLoaderRoute: typeof OfficerLayoutRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/grade-analysis/_layout': {
      id: '/grade-analysis/_layout'
      path: ''
      fullPath: '/grade-analysis'
      preLoaderRoute: typeof GradeAnalysisLayoutRouteImport
      parentRoute: typeof GradeAnalysisRouteRoute
    }
    '/explore/university': {
      id: '/explore/university'
      path: '/explore/university'
      fullPath: '/explore/university'
      preLoaderRoute: typeof ExploreUniversityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/recruitment-unit': {
      id: '/explore/recruitment-unit'
      path: '/explore/recruitment-unit'
      fullPath: '/explore/recruitment-unit'
      preLoaderRoute: typeof ExploreRecruitmentUnitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/admission': {
      id: '/explore/admission'
      path: '/explore/admission'
      fullPath: '/explore/admission'
      preLoaderRoute: typeof ExploreAdmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation/_layout': {
      id: '/evaluation/_layout'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationLayoutRouteImport
      parentRoute: typeof EvaluationRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/official/notice/': {
      id: '/official/notice/'
      path: '/official/notice'
      fullPath: '/official/notice'
      preLoaderRoute: typeof OfficialNoticeIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/_layout/school-record': {
      id: '/users/_layout/school-record'
      path: '/school-record'
      fullPath: '/users/school-record'
      preLoaderRoute: typeof UsersLayoutSchoolRecordLazyRouteImport
      parentRoute: typeof UsersLayoutRoute
    }
    '/users/_layout/profile': {
      id: '/users/_layout/profile'
      path: '/profile'
      fullPath: '/users/profile'
      preLoaderRoute: typeof UsersLayoutProfileLazyRouteImport
      parentRoute: typeof UsersLayoutRoute
    }
    '/users/_layout/additional-file': {
      id: '/users/_layout/additional-file'
      path: '/additional-file'
      fullPath: '/users/additional-file'
      preLoaderRoute: typeof UsersLayoutAdditionalFileLazyRouteImport
      parentRoute: typeof UsersLayoutRoute
    }
    '/sb/_layout/target-university': {
      id: '/sb/_layout/target-university'
      path: '/target-university'
      fullPath: '/sb/target-university'
      preLoaderRoute: typeof SbLayoutTargetUniversityLazyRouteImport
      parentRoute: typeof SbLayoutRoute
    }
    '/sb/_layout/subject': {
      id: '/sb/_layout/subject'
      path: '/subject'
      fullPath: '/sb/subject'
      preLoaderRoute: typeof SbLayoutSubjectLazyRouteImport
      parentRoute: typeof SbLayoutRoute
    }
    '/sb/_layout/setuk': {
      id: '/sb/_layout/setuk'
      path: '/setuk'
      fullPath: '/sb/setuk'
      preLoaderRoute: typeof SbLayoutSetukLazyRouteImport
      parentRoute: typeof SbLayoutRoute
    }
    '/sb/_layout/school-record': {
      id: '/sb/_layout/school-record'
      path: '/school-record'
      fullPath: '/sb/school-record'
      preLoaderRoute: typeof SbLayoutSchoolRecordLazyRouteImport
      parentRoute: typeof SbLayoutRoute
    }
    '/sb/_layout/request': {
      id: '/sb/_layout/request'
      path: '/request'
      fullPath: '/sb/request'
      preLoaderRoute: typeof SbLayoutRequestLazyRouteImport
      parentRoute: typeof SbLayoutRoute
    }
    '/sb/_layout/performance': {
      id: '/sb/_layout/performance'
      path: '/performance'
      fullPath: '/sb/performance'
      preLoaderRoute: typeof SbLayoutPerformanceLazyRouteImport
      parentRoute: typeof SbLayoutRoute
    }
    '/sb/_layout/nonsul': {
      id: '/sb/_layout/nonsul'
      path: '/nonsul'
      fullPath: '/sb/nonsul'
      preLoaderRoute: typeof SbLayoutNonsulLazyRouteImport
      parentRoute: typeof SbLayoutRoute
    }
    '/sb/_layout/material-analysis': {
      id: '/sb/_layout/material-analysis'
      path: '/material-analysis'
      fullPath: '/sb/material-analysis'
      preLoaderRoute: typeof SbLayoutMaterialAnalysisLazyRouteImport
      parentRoute: typeof SbLayoutRoute
    }
    '/sb/_layout/evaluation-list': {
      id: '/sb/_layout/evaluation-list'
      path: '/evaluation-list'
      fullPath: '/sb/evaluation-list'
      preLoaderRoute: typeof SbLayoutEvaluationListLazyRouteImport
      parentRoute: typeof SbLayoutRoute
    }
    '/sb/_layout/evaluation': {
      id: '/sb/_layout/evaluation'
      path: '/evaluation'
      fullPath: '/sb/evaluation'
      preLoaderRoute: typeof SbLayoutEvaluationLazyRouteImport
      parentRoute: typeof SbLayoutRoute
    }
    '/sb/_layout/creative-activity': {
      id: '/sb/_layout/creative-activity'
      path: '/creative-activity'
      fullPath: '/sb/creative-activity'
      preLoaderRoute: typeof SbLayoutCreativeActivityLazyRouteImport
      parentRoute: typeof SbLayoutRoute
    }
    '/sb/_layout/comprehensive': {
      id: '/sb/_layout/comprehensive'
      path: '/comprehensive'
      fullPath: '/sb/comprehensive'
      preLoaderRoute: typeof SbLayoutComprehensiveLazyRouteImport
      parentRoute: typeof SbLayoutRoute
    }
    '/sb/_layout/compatibility': {
      id: '/sb/_layout/compatibility'
      path: '/compatibility'
      fullPath: '/sb/compatibility'
      preLoaderRoute: typeof SbLayoutCompatibilityLazyRouteImport
      parentRoute: typeof SbLayoutRoute
    }
    '/sb/_layout/build': {
      id: '/sb/_layout/build'
      path: '/build'
      fullPath: '/sb/build'
      preLoaderRoute: typeof SbLayoutBuildLazyRouteImport
      parentRoute: typeof SbLayoutRoute
    }
    '/sb/_layout/attendance': {
      id: '/sb/_layout/attendance'
      path: '/attendance'
      fullPath: '/sb/attendance'
      preLoaderRoute: typeof SbLayoutAttendanceLazyRouteImport
      parentRoute: typeof SbLayoutRoute
    }
    '/official/notice/$postId': {
      id: '/official/notice/$postId'
      path: '/official/notice/$postId'
      fullPath: '/official/notice/$postId'
      preLoaderRoute: typeof OfficialNoticePostIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/_layout/profile': {
      id: '/officer/_layout/profile'
      path: '/profile'
      fullPath: '/officer/profile'
      preLoaderRoute: typeof OfficerLayoutProfileLazyRouteImport
      parentRoute: typeof OfficerLayoutRoute
    }
    '/grade-analysis/_layout/subject': {
      id: '/grade-analysis/_layout/subject'
      path: '/subject'
      fullPath: '/grade-analysis/subject'
      preLoaderRoute: typeof GradeAnalysisLayoutSubjectLazyRouteImport
      parentRoute: typeof GradeAnalysisLayoutRoute
    }
    '/grade-analysis/_layout/school-record': {
      id: '/grade-analysis/_layout/school-record'
      path: '/school-record'
      fullPath: '/grade-analysis/school-record'
      preLoaderRoute: typeof GradeAnalysisLayoutSchoolRecordLazyRouteImport
      parentRoute: typeof GradeAnalysisLayoutRoute
    }
    '/grade-analysis/_layout/request': {
      id: '/grade-analysis/_layout/request'
      path: '/request'
      fullPath: '/grade-analysis/request'
      preLoaderRoute: typeof GradeAnalysisLayoutRequestLazyRouteImport
      parentRoute: typeof GradeAnalysisLayoutRoute
    }
    '/grade-analysis/_layout/performance': {
      id: '/grade-analysis/_layout/performance'
      path: '/performance'
      fullPath: '/grade-analysis/performance'
      preLoaderRoute: typeof GradeAnalysisLayoutPerformanceLazyRouteImport
      parentRoute: typeof GradeAnalysisLayoutRoute
    }
    '/grade-analysis/_layout/nonsul': {
      id: '/grade-analysis/_layout/nonsul'
      path: '/nonsul'
      fullPath: '/grade-analysis/nonsul'
      preLoaderRoute: typeof GradeAnalysisLayoutNonsulLazyRouteImport
      parentRoute: typeof GradeAnalysisLayoutRoute
    }
    '/grade-analysis/_layout/evaluation-list': {
      id: '/grade-analysis/_layout/evaluation-list'
      path: '/evaluation-list'
      fullPath: '/grade-analysis/evaluation-list'
      preLoaderRoute: typeof GradeAnalysisLayoutEvaluationListLazyRouteImport
      parentRoute: typeof GradeAnalysisLayoutRoute
    }
    '/grade-analysis/_layout/comprehensive': {
      id: '/grade-analysis/_layout/comprehensive'
      path: '/comprehensive'
      fullPath: '/grade-analysis/comprehensive'
      preLoaderRoute: typeof GradeAnalysisLayoutComprehensiveLazyRouteImport
      parentRoute: typeof GradeAnalysisLayoutRoute
    }
    '/evaluation/_layout/request': {
      id: '/evaluation/_layout/request'
      path: '/request'
      fullPath: '/evaluation/request'
      preLoaderRoute: typeof EvaluationLayoutRequestLazyRouteImport
      parentRoute: typeof EvaluationLayoutRoute
    }
    '/evaluation/_layout/list': {
      id: '/evaluation/_layout/list'
      path: '/list'
      fullPath: '/evaluation/list'
      preLoaderRoute: typeof EvaluationLayoutListLazyRouteImport
      parentRoute: typeof EvaluationLayoutRoute
    }
    '/evaluation/_layout/compatibility': {
      id: '/evaluation/_layout/compatibility'
      path: '/compatibility'
      fullPath: '/evaluation/compatibility'
      preLoaderRoute: typeof EvaluationLayoutCompatibilityLazyRouteImport
      parentRoute: typeof EvaluationLayoutRoute
    }
    '/auth/oauth/callback': {
      id: '/auth/oauth/callback'
      path: '/auth/oauth/callback'
      fullPath: '/auth/oauth/callback'
      preLoaderRoute: typeof AuthOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/_layout/payment/': {
      id: '/users/_layout/payment/'
      path: '/payment'
      fullPath: '/users/payment'
      preLoaderRoute: typeof UsersLayoutPaymentIndexLazyRouteImport
      parentRoute: typeof UsersLayoutRoute
    }
    '/officer/_layout/apply/': {
      id: '/officer/_layout/apply/'
      path: '/apply'
      fullPath: '/officer/apply'
      preLoaderRoute: typeof OfficerLayoutApplyIndexLazyRouteImport
      parentRoute: typeof OfficerLayoutRoute
    }
    '/evaluation/_layout/self/': {
      id: '/evaluation/_layout/self/'
      path: '/self'
      fullPath: '/evaluation/self'
      preLoaderRoute: typeof EvaluationLayoutSelfIndexLazyRouteImport
      parentRoute: typeof EvaluationLayoutRoute
    }
    '/users/_layout/payment/$id': {
      id: '/users/_layout/payment/$id'
      path: '/payment/$id'
      fullPath: '/users/payment/$id'
      preLoaderRoute: typeof UsersLayoutPaymentIdLazyRouteImport
      parentRoute: typeof UsersLayoutRoute
    }
    '/officer/_layout/apply/$evaluationId': {
      id: '/officer/_layout/apply/$evaluationId'
      path: '/apply/$evaluationId'
      fullPath: '/officer/apply/$evaluationId'
      preLoaderRoute: typeof OfficerLayoutApplyEvaluationIdLazyRouteImport
      parentRoute: typeof OfficerLayoutRoute
    }
  }
}

interface GradeAnalysisLayoutRouteChildren {
  GradeAnalysisLayoutComprehensiveLazyRoute: typeof GradeAnalysisLayoutComprehensiveLazyRoute
  GradeAnalysisLayoutEvaluationListLazyRoute: typeof GradeAnalysisLayoutEvaluationListLazyRoute
  GradeAnalysisLayoutNonsulLazyRoute: typeof GradeAnalysisLayoutNonsulLazyRoute
  GradeAnalysisLayoutPerformanceLazyRoute: typeof GradeAnalysisLayoutPerformanceLazyRoute
  GradeAnalysisLayoutRequestLazyRoute: typeof GradeAnalysisLayoutRequestLazyRoute
  GradeAnalysisLayoutSchoolRecordLazyRoute: typeof GradeAnalysisLayoutSchoolRecordLazyRoute
  GradeAnalysisLayoutSubjectLazyRoute: typeof GradeAnalysisLayoutSubjectLazyRoute
}

const GradeAnalysisLayoutRouteChildren: GradeAnalysisLayoutRouteChildren = {
  GradeAnalysisLayoutComprehensiveLazyRoute:
    GradeAnalysisLayoutComprehensiveLazyRoute,
  GradeAnalysisLayoutEvaluationListLazyRoute:
    GradeAnalysisLayoutEvaluationListLazyRoute,
  GradeAnalysisLayoutNonsulLazyRoute: GradeAnalysisLayoutNonsulLazyRoute,
  GradeAnalysisLayoutPerformanceLazyRoute:
    GradeAnalysisLayoutPerformanceLazyRoute,
  GradeAnalysisLayoutRequestLazyRoute: GradeAnalysisLayoutRequestLazyRoute,
  GradeAnalysisLayoutSchoolRecordLazyRoute:
    GradeAnalysisLayoutSchoolRecordLazyRoute,
  GradeAnalysisLayoutSubjectLazyRoute: GradeAnalysisLayoutSubjectLazyRoute,
}

const GradeAnalysisLayoutRouteWithChildren =
  GradeAnalysisLayoutRoute._addFileChildren(GradeAnalysisLayoutRouteChildren)

interface GradeAnalysisRouteRouteChildren {
  GradeAnalysisLayoutRoute: typeof GradeAnalysisLayoutRouteWithChildren
  GradeAnalysisIndexLazyRoute: typeof GradeAnalysisIndexLazyRoute
}

const GradeAnalysisRouteRouteChildren: GradeAnalysisRouteRouteChildren = {
  GradeAnalysisLayoutRoute: GradeAnalysisLayoutRouteWithChildren,
  GradeAnalysisIndexLazyRoute: GradeAnalysisIndexLazyRoute,
}

const GradeAnalysisRouteRouteWithChildren =
  GradeAnalysisRouteRoute._addFileChildren(GradeAnalysisRouteRouteChildren)

interface SbLayoutRouteChildren {
  SbLayoutAttendanceLazyRoute: typeof SbLayoutAttendanceLazyRoute
  SbLayoutBuildLazyRoute: typeof SbLayoutBuildLazyRoute
  SbLayoutCompatibilityLazyRoute: typeof SbLayoutCompatibilityLazyRoute
  SbLayoutComprehensiveLazyRoute: typeof SbLayoutComprehensiveLazyRoute
  SbLayoutCreativeActivityLazyRoute: typeof SbLayoutCreativeActivityLazyRoute
  SbLayoutEvaluationLazyRoute: typeof SbLayoutEvaluationLazyRoute
  SbLayoutEvaluationListLazyRoute: typeof SbLayoutEvaluationListLazyRoute
  SbLayoutMaterialAnalysisLazyRoute: typeof SbLayoutMaterialAnalysisLazyRoute
  SbLayoutNonsulLazyRoute: typeof SbLayoutNonsulLazyRoute
  SbLayoutPerformanceLazyRoute: typeof SbLayoutPerformanceLazyRoute
  SbLayoutRequestLazyRoute: typeof SbLayoutRequestLazyRoute
  SbLayoutSchoolRecordLazyRoute: typeof SbLayoutSchoolRecordLazyRoute
  SbLayoutSetukLazyRoute: typeof SbLayoutSetukLazyRoute
  SbLayoutSubjectLazyRoute: typeof SbLayoutSubjectLazyRoute
  SbLayoutTargetUniversityLazyRoute: typeof SbLayoutTargetUniversityLazyRoute
}

const SbLayoutRouteChildren: SbLayoutRouteChildren = {
  SbLayoutAttendanceLazyRoute: SbLayoutAttendanceLazyRoute,
  SbLayoutBuildLazyRoute: SbLayoutBuildLazyRoute,
  SbLayoutCompatibilityLazyRoute: SbLayoutCompatibilityLazyRoute,
  SbLayoutComprehensiveLazyRoute: SbLayoutComprehensiveLazyRoute,
  SbLayoutCreativeActivityLazyRoute: SbLayoutCreativeActivityLazyRoute,
  SbLayoutEvaluationLazyRoute: SbLayoutEvaluationLazyRoute,
  SbLayoutEvaluationListLazyRoute: SbLayoutEvaluationListLazyRoute,
  SbLayoutMaterialAnalysisLazyRoute: SbLayoutMaterialAnalysisLazyRoute,
  SbLayoutNonsulLazyRoute: SbLayoutNonsulLazyRoute,
  SbLayoutPerformanceLazyRoute: SbLayoutPerformanceLazyRoute,
  SbLayoutRequestLazyRoute: SbLayoutRequestLazyRoute,
  SbLayoutSchoolRecordLazyRoute: SbLayoutSchoolRecordLazyRoute,
  SbLayoutSetukLazyRoute: SbLayoutSetukLazyRoute,
  SbLayoutSubjectLazyRoute: SbLayoutSubjectLazyRoute,
  SbLayoutTargetUniversityLazyRoute: SbLayoutTargetUniversityLazyRoute,
}

const SbLayoutRouteWithChildren = SbLayoutRoute._addFileChildren(
  SbLayoutRouteChildren,
)

interface SbRouteRouteChildren {
  SbLayoutRoute: typeof SbLayoutRouteWithChildren
  SbDashboardLazyRoute: typeof SbDashboardLazyRoute
  SbIndexLazyRoute: typeof SbIndexLazyRoute
}

const SbRouteRouteChildren: SbRouteRouteChildren = {
  SbLayoutRoute: SbLayoutRouteWithChildren,
  SbDashboardLazyRoute: SbDashboardLazyRoute,
  SbIndexLazyRoute: SbIndexLazyRoute,
}

const SbRouteRouteWithChildren =
  SbRouteRoute._addFileChildren(SbRouteRouteChildren)

interface TryRouteRouteChildren {
  TryIndexLazyRoute: typeof TryIndexLazyRoute
}

const TryRouteRouteChildren: TryRouteRouteChildren = {
  TryIndexLazyRoute: TryIndexLazyRoute,
}

const TryRouteRouteWithChildren = TryRouteRoute._addFileChildren(
  TryRouteRouteChildren,
)

interface EvaluationLayoutRouteChildren {
  EvaluationLayoutCompatibilityLazyRoute: typeof EvaluationLayoutCompatibilityLazyRoute
  EvaluationLayoutListLazyRoute: typeof EvaluationLayoutListLazyRoute
  EvaluationLayoutRequestLazyRoute: typeof EvaluationLayoutRequestLazyRoute
  EvaluationLayoutSelfIndexLazyRoute: typeof EvaluationLayoutSelfIndexLazyRoute
}

const EvaluationLayoutRouteChildren: EvaluationLayoutRouteChildren = {
  EvaluationLayoutCompatibilityLazyRoute:
    EvaluationLayoutCompatibilityLazyRoute,
  EvaluationLayoutListLazyRoute: EvaluationLayoutListLazyRoute,
  EvaluationLayoutRequestLazyRoute: EvaluationLayoutRequestLazyRoute,
  EvaluationLayoutSelfIndexLazyRoute: EvaluationLayoutSelfIndexLazyRoute,
}

const EvaluationLayoutRouteWithChildren =
  EvaluationLayoutRoute._addFileChildren(EvaluationLayoutRouteChildren)

interface EvaluationRouteChildren {
  EvaluationLayoutRoute: typeof EvaluationLayoutRouteWithChildren
  EvaluationIndexLazyRoute: typeof EvaluationIndexLazyRoute
}

const EvaluationRouteChildren: EvaluationRouteChildren = {
  EvaluationLayoutRoute: EvaluationLayoutRouteWithChildren,
  EvaluationIndexLazyRoute: EvaluationIndexLazyRoute,
}

const EvaluationRouteWithChildren = EvaluationRoute._addFileChildren(
  EvaluationRouteChildren,
)

interface OfficerLayoutRouteChildren {
  OfficerLayoutProfileLazyRoute: typeof OfficerLayoutProfileLazyRoute
  OfficerLayoutApplyEvaluationIdLazyRoute: typeof OfficerLayoutApplyEvaluationIdLazyRoute
  OfficerLayoutApplyIndexLazyRoute: typeof OfficerLayoutApplyIndexLazyRoute
}

const OfficerLayoutRouteChildren: OfficerLayoutRouteChildren = {
  OfficerLayoutProfileLazyRoute: OfficerLayoutProfileLazyRoute,
  OfficerLayoutApplyEvaluationIdLazyRoute:
    OfficerLayoutApplyEvaluationIdLazyRoute,
  OfficerLayoutApplyIndexLazyRoute: OfficerLayoutApplyIndexLazyRoute,
}

const OfficerLayoutRouteWithChildren = OfficerLayoutRoute._addFileChildren(
  OfficerLayoutRouteChildren,
)

interface OfficerRouteChildren {
  OfficerLayoutRoute: typeof OfficerLayoutRouteWithChildren
}

const OfficerRouteChildren: OfficerRouteChildren = {
  OfficerLayoutRoute: OfficerLayoutRouteWithChildren,
}

const OfficerRouteWithChildren =
  OfficerRoute._addFileChildren(OfficerRouteChildren)

interface UsersLayoutRouteChildren {
  UsersLayoutAdditionalFileLazyRoute: typeof UsersLayoutAdditionalFileLazyRoute
  UsersLayoutProfileLazyRoute: typeof UsersLayoutProfileLazyRoute
  UsersLayoutSchoolRecordLazyRoute: typeof UsersLayoutSchoolRecordLazyRoute
  UsersLayoutPaymentIdLazyRoute: typeof UsersLayoutPaymentIdLazyRoute
  UsersLayoutPaymentIndexLazyRoute: typeof UsersLayoutPaymentIndexLazyRoute
}

const UsersLayoutRouteChildren: UsersLayoutRouteChildren = {
  UsersLayoutAdditionalFileLazyRoute: UsersLayoutAdditionalFileLazyRoute,
  UsersLayoutProfileLazyRoute: UsersLayoutProfileLazyRoute,
  UsersLayoutSchoolRecordLazyRoute: UsersLayoutSchoolRecordLazyRoute,
  UsersLayoutPaymentIdLazyRoute: UsersLayoutPaymentIdLazyRoute,
  UsersLayoutPaymentIndexLazyRoute: UsersLayoutPaymentIndexLazyRoute,
}

const UsersLayoutRouteWithChildren = UsersLayoutRoute._addFileChildren(
  UsersLayoutRouteChildren,
)

interface UsersRouteChildren {
  UsersLayoutRoute: typeof UsersLayoutRouteWithChildren
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersLayoutRoute: UsersLayoutRouteWithChildren,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GradeAnalysisRouteRoute: GradeAnalysisRouteRouteWithChildren,
  SbRouteRoute: SbRouteRouteWithChildren,
  TryRouteRoute: TryRouteRouteWithChildren,
  H1Route: H1Route,
  H2Route: H2Route,
  H3Route: H3Route,
  H4Route: H4Route,
  PricingRoute: PricingRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  EvaluationRoute: EvaluationRouteWithChildren,
  ExploreAdmissionRoute: ExploreAdmissionRoute,
  ExploreRecruitmentUnitRoute: ExploreRecruitmentUnitRoute,
  ExploreUniversityRoute: ExploreUniversityRoute,
  OfficerRoute: OfficerRouteWithChildren,
  OrderProductIdRoute: OrderProductIdRoute,
  TestAuthMeRoute: TestAuthMeRoute,
  TestLoginDebugRoute: TestLoginDebugRoute,
  UsersRoute: UsersRouteWithChildren,
  naverRedirectLazyRoute: naverRedirectLazyRoute,
  AnalysisPerformanceLazyRoute: AnalysisPerformanceLazyRoute,
  ExplainPrivacyLazyRoute: ExplainPrivacyLazyRoute,
  ExplainRefundLazyRoute: ExplainRefundLazyRoute,
  ExplainServiceLazyRoute: ExplainServiceLazyRoute,
  ExploreSusiJonghapLazyRoute: ExploreSusiJonghapLazyRoute,
  ExploreSusiKyokwaLazyRoute: ExploreSusiKyokwaLazyRoute,
  OfficialFaqLazyRoute: OfficialFaqLazyRoute,
  OfficialGuideLazyRoute: OfficialGuideLazyRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  AnalysisIndexLazyRoute: AnalysisIndexLazyRoute,
  AuthOauthCallbackRoute: AuthOauthCallbackRoute,
  OfficialNoticePostIdLazyRoute: OfficialNoticePostIdLazyRoute,
  OfficialNoticeIndexLazyRoute: OfficialNoticeIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
